 # workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'

      - name: Build Binaries
        run: |
          mkdir -p builds/compressed
          go get github.com/mitchellh/gox
          gox --output "builds/splatstatsuploader-{{.OS}}-{{.Arch}}" -osarch="darwin/amd64 linux/amd64 freebsd/amd64 openbsd/amd64 windows/amd64 netbsd/amd64 linux/mips64 linux/s390x linux/mips64le"
          cd builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
           builds/compressed/*

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Upload Binaries
        run: |
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} --replace ${{ steps.previoustag.outputs.tag }} builds/compressed/
